var sample = " Time to Lead ";
console.log(sample.endsWith(" "));
console.log(sample.startsWith("t"));
console.log(sample.includes("t"));
console.log(sample.concat(" yes"));
console.log(sample.charAt(4));
console.log(sample.toUpperCase());
console.log(sample.toLowerCase());
console.log(sample.indexOf("e"));
console.log(sample.lastIndexOf("e"));
console.log(sample.split(" "));
console.log(sample.trimStart());
console.log(sample.trimEnd());
console.log(sample.trim());
console.log(sample.substring(5, 10));
console.log(sample.slice(3, 8));
console.log(sample.search("t"));
console.log(sample.replace("to Lead", "for victory"));
console.log(sample.repeat(3));
